# Generated by Django 5.2.8 on 2025-11-12 13:20

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryBook',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('category', models.CharField(blank=True, max_length=100, null=True)),
                ('stock', models.IntegerField(default=0)),
                ('condition', models.CharField(choices=[('새 것', '새 것'), ('양호', '양호'), ('낡음', '낡음')], default='양호', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='books', to='db_core.institution')),
            ],
        ),
    ]
