# Generated by Django 5.2.8 on 2025-11-15 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0003_booksupplyrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorybook',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='inventorybook',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='inventorybook',
            name='condition',
            field=models.CharField(choices=[('새 책', '새 책'), ('양호', '양호'), ('손상', '손상')], default='양호', max_length=10),
        ),
    ]
