# Generated by Django 5.2.8 on 2025-11-16 09:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db_core', '0004_inventorybook_description_inventorybook_genre_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookSupplyTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('requested_amount', models.IntegerField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='db_core.inventorybook')),
                ('requester_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_transaction', to='db_core.institution')),
                ('supplier_institution', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='supplied_transaction', to='db_core.institution')),
            ],
        ),
    ]
